name             'demo-cookbook'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures demo-cookbook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends         'apache2'
depends         'users'
depends         'vim'
depends         'ntp'
depends         'simple_iptables'
depends         'tomcat-all'
depends         'database'
depends         'postgresql'
depends         'java'
depends         'yum-epel'

